#ifndef __INCLUDE_ICMP_H
#define __INCLUDE_ICMP_H

/*
 * ICMP header definitions
 */
#define ICMP_HEADER_LEN         4

#define ICMP_TYPE_OFFSET        0
#define ICMP_CODE_OFFSET        1
#define ICMP_CKSUM_OFFSET       2
#define ICMP_DATA_OFFSET        4

#define ICMP_GET_TYPE(ICMP)     READ_BYTE((ICMP), ICMP_TYPE_OFFSET)
#define ICMP_SET_TYPE(ICMP, V)  WRITE_BYTE((ICMP), ICMP_TYPE_OFFSET, V)
#define ICMP_TYPE_ECHO_REPLY    0
#define ICMP_TYPE_ECHO_REQUEST  8

#define ICMP_GET_CODE(ICMP)     READ_BYTE((ICMP), ICMP_CODE_OFFSET)
#define ICMP_SET_CODE(ICMP, V)  WRITE_BYTE((ICMP), ICMP_CODE_OFFSET, V)

#define ICMP_CKSUM_H(ICMP)      (ICMP)[ICMP_CKSUM_OFFSET+0]
#define ICMP_CKSUM_L(ICMP)      (ICMP)[ICMP_CKSUM_OFFSET+1]
#define ICMP_GET_CKSUM(ICMP)    READ_BYTE((ICMP), ICMP_CKSUM_OFFSET)
#define ICMP_SET_CKSUM(ICMP, V) WRITE_BYTE((ICMP), ICMP_CKSUM_OFFSET, V)

#define ICMP_GET_DATA(ICMP)     READ_BYTE((ICMP), ICMP_DATA_OFFSET)
#define ICMP_SET_DATA(ICMP, V)  WRITE_BYTE((ICMP), ICMP_DATA_OFFSET, V)


#endif /* __INCLUDE_ICMP_H */
